[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "index.html"]

[serve]
addresses = ["127.0.0.1"]
port = 8044
open = false

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "cp -r src/static/* dist/ 2>/dev/null || true"]
